/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReparatiesRouteImport } from './routes/reparaties'
import { Route as AfspraakRouteImport } from './routes/afspraak'
import { Route as IndexRouteImport } from './routes/index'

const ReparatiesRoute = ReparatiesRouteImport.update({
  id: '/reparaties',
  path: '/reparaties',
  getParentRoute: () => rootRouteImport,
} as any)
const AfspraakRoute = AfspraakRouteImport.update({
  id: '/afspraak',
  path: '/afspraak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/reparaties': typeof ReparatiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/reparaties': typeof ReparatiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afspraak': typeof AfspraakRoute
  '/reparaties': typeof ReparatiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/afspraak' | '/reparaties'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/afspraak' | '/reparaties'
  id: '__root__' | '/' | '/afspraak' | '/reparaties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfspraakRoute: typeof AfspraakRoute
  ReparatiesRoute: typeof ReparatiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reparaties': {
      id: '/reparaties'
      path: '/reparaties'
      fullPath: '/reparaties'
      preLoaderRoute: typeof ReparatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afspraak': {
      id: '/afspraak'
      path: '/afspraak'
      fullPath: '/afspraak'
      preLoaderRoute: typeof AfspraakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfspraakRoute: AfspraakRoute,
  ReparatiesRoute: ReparatiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
