/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as ReparatiesRouteImport } from './routes/reparaties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PakketpuntRouteImport } from './routes/pakketpunt'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AfspraakRouteImport } from './routes/afspraak'
import { Route as AccessoiresRouteImport } from './routes/accessoires'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSlotsRouteImport } from './routes/api/public/slots'
import { Route as ApiPublicAfspraakRouteImport } from './routes/api/public/afspraak'
import { Route as ApiPublicAfspraakIcsRouteImport } from './routes/api/public/afspraak.ics'

const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparatiesRoute = ReparatiesRouteImport.update({
  id: '/reparaties',
  path: '/reparaties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PakketpuntRoute = PakketpuntRouteImport.update({
  id: '/pakketpunt',
  path: '/pakketpunt',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AfspraakRoute = AfspraakRouteImport.update({
  id: '/afspraak',
  path: '/afspraak',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresRoute = AccessoiresRouteImport.update({
  id: '/accessoires',
  path: '/accessoires',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlotsRoute = ApiPublicSlotsRouteImport.update({
  id: '/api/public/slots',
  path: '/api/public/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAfspraakRoute = ApiPublicAfspraakRouteImport.update({
  id: '/api/public/afspraak',
  path: '/api/public/afspraak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAfspraakIcsRoute = ApiPublicAfspraakIcsRouteImport.update({
  id: '/ics',
  path: '/ics',
  getParentRoute: () => ApiPublicAfspraakRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/afspraak': typeof AfspraakRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/over-ons': typeof OverOnsRoute
  '/pakketpunt': typeof PakketpuntRoute
  '/privacy': typeof PrivacyRoute
  '/reparaties': typeof ReparatiesRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/api/public/afspraak': typeof ApiPublicAfspraakRouteWithChildren
  '/api/public/slots': typeof ApiPublicSlotsRoute
  '/api/public/afspraak/ics': typeof ApiPublicAfspraakIcsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/afspraak': typeof AfspraakRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/over-ons': typeof OverOnsRoute
  '/pakketpunt': typeof PakketpuntRoute
  '/privacy': typeof PrivacyRoute
  '/reparaties': typeof ReparatiesRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/api/public/afspraak': typeof ApiPublicAfspraakRouteWithChildren
  '/api/public/slots': typeof ApiPublicSlotsRoute
  '/api/public/afspraak/ics': typeof ApiPublicAfspraakIcsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/afspraak': typeof AfspraakRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/over-ons': typeof OverOnsRoute
  '/pakketpunt': typeof PakketpuntRoute
  '/privacy': typeof PrivacyRoute
  '/reparaties': typeof ReparatiesRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/api/public/afspraak': typeof ApiPublicAfspraakRouteWithChildren
  '/api/public/slots': typeof ApiPublicSlotsRoute
  '/api/public/afspraak/ics': typeof ApiPublicAfspraakIcsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessoires'
    | '/afspraak'
    | '/contact'
    | '/cookies'
    | '/over-ons'
    | '/pakketpunt'
    | '/privacy'
    | '/reparaties'
    | '/voorwaarden'
    | '/api/public/afspraak'
    | '/api/public/slots'
    | '/api/public/afspraak/ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessoires'
    | '/afspraak'
    | '/contact'
    | '/cookies'
    | '/over-ons'
    | '/pakketpunt'
    | '/privacy'
    | '/reparaties'
    | '/voorwaarden'
    | '/api/public/afspraak'
    | '/api/public/slots'
    | '/api/public/afspraak/ics'
  id:
    | '__root__'
    | '/'
    | '/accessoires'
    | '/afspraak'
    | '/contact'
    | '/cookies'
    | '/over-ons'
    | '/pakketpunt'
    | '/privacy'
    | '/reparaties'
    | '/voorwaarden'
    | '/api/public/afspraak'
    | '/api/public/slots'
    | '/api/public/afspraak/ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoiresRoute: typeof AccessoiresRoute
  AfspraakRoute: typeof AfspraakRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  OverOnsRoute: typeof OverOnsRoute
  PakketpuntRoute: typeof PakketpuntRoute
  PrivacyRoute: typeof PrivacyRoute
  ReparatiesRoute: typeof ReparatiesRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  ApiPublicAfspraakRoute: typeof ApiPublicAfspraakRouteWithChildren
  ApiPublicSlotsRoute: typeof ApiPublicSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparaties': {
      id: '/reparaties'
      path: '/reparaties'
      fullPath: '/reparaties'
      preLoaderRoute: typeof ReparatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakketpunt': {
      id: '/pakketpunt'
      path: '/pakketpunt'
      fullPath: '/pakketpunt'
      preLoaderRoute: typeof PakketpuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afspraak': {
      id: '/afspraak'
      path: '/afspraak'
      fullPath: '/afspraak'
      preLoaderRoute: typeof AfspraakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires': {
      id: '/accessoires'
      path: '/accessoires'
      fullPath: '/accessoires'
      preLoaderRoute: typeof AccessoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slots': {
      id: '/api/public/slots'
      path: '/api/public/slots'
      fullPath: '/api/public/slots'
      preLoaderRoute: typeof ApiPublicSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/afspraak': {
      id: '/api/public/afspraak'
      path: '/api/public/afspraak'
      fullPath: '/api/public/afspraak'
      preLoaderRoute: typeof ApiPublicAfspraakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/afspraak/ics': {
      id: '/api/public/afspraak/ics'
      path: '/ics'
      fullPath: '/api/public/afspraak/ics'
      preLoaderRoute: typeof ApiPublicAfspraakIcsRouteImport
      parentRoute: typeof ApiPublicAfspraakRoute
    }
  }
}

interface ApiPublicAfspraakRouteChildren {
  ApiPublicAfspraakIcsRoute: typeof ApiPublicAfspraakIcsRoute
}

const ApiPublicAfspraakRouteChildren: ApiPublicAfspraakRouteChildren = {
  ApiPublicAfspraakIcsRoute: ApiPublicAfspraakIcsRoute,
}

const ApiPublicAfspraakRouteWithChildren =
  ApiPublicAfspraakRoute._addFileChildren(ApiPublicAfspraakRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoiresRoute: AccessoiresRoute,
  AfspraakRoute: AfspraakRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  OverOnsRoute: OverOnsRoute,
  PakketpuntRoute: PakketpuntRoute,
  PrivacyRoute: PrivacyRoute,
  ReparatiesRoute: ReparatiesRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  ApiPublicAfspraakRoute: ApiPublicAfspraakRouteWithChildren,
  ApiPublicSlotsRoute: ApiPublicSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
